# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OkSIBn4_QGzoxYhxBAfF13OGHyFDKvAw
"""

suma = 0

while True:
    liczba = int(input("Podaj liczbę (0 kończy wprowadzanie): "))

    if liczba == 0:
        break

    suma += liczba

print("Suma podanych liczb to:", suma)